// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHBE-SBfCS2_htJLz_vyxmAJeKpXYoC8M',
    appId: '1:1034030721878:web:a1e94dd0228da9193a84f7',
    messagingSenderId: '1034030721878',
    projectId: 'fluxhub-997b2',
    authDomain: 'fluxhub-997b2.firebaseapp.com',
    storageBucket: 'fluxhub-997b2.firebasestorage.app',
    measurementId: 'G-MKFLDJEGDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2tTBeApa_FEvQNStDN4ekPv3ds3JQkBk',
    appId: '1:1034030721878:android:ddd10b91343fead03a84f7',
    messagingSenderId: '1034030721878',
    projectId: 'fluxhub-997b2',
    storageBucket: 'fluxhub-997b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTJbcGdW2HGYsPjU3xzPZ3K7g98wD5CqE',
    appId: '1:1034030721878:ios:823998680bf17e033a84f7',
    messagingSenderId: '1034030721878',
    projectId: 'fluxhub-997b2',
    storageBucket: 'fluxhub-997b2.firebasestorage.app',
    iosBundleId: 'com.fuxhub.hubFlux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTJbcGdW2HGYsPjU3xzPZ3K7g98wD5CqE',
    appId: '1:1034030721878:ios:823998680bf17e033a84f7',
    messagingSenderId: '1034030721878',
    projectId: 'fluxhub-997b2',
    storageBucket: 'fluxhub-997b2.firebasestorage.app',
    iosBundleId: 'com.fuxhub.hubFlux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHBE-SBfCS2_htJLz_vyxmAJeKpXYoC8M',
    appId: '1:1034030721878:web:a1e94dd0228da9193a84f7',
    messagingSenderId: '1034030721878',
    projectId: 'fluxhub-997b2',
    authDomain: 'fluxhub-997b2.firebaseapp.com',
    storageBucket: 'fluxhub-997b2.firebasestorage.app',
    measurementId: 'G-MKFLDJEGDV',
  );
}

